name: flutter_fetch_widget
description: Make simple http requests with a widget.
version: 0.0.1
author: Andres Araujo
homepage:

dependencies:
  http: "^0.11.3+16"
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0

flutter:
