name: flutter_fetch_widget
description: Make simple http requests with a widget.
version: 0.0.1+1
author: Andres Araujo<a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/flutter_fetch_widget

dependencies:
  http: "^0.11.3+16"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^0.12.0

flutter:

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"